spring.application.name=security
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=SECURITY
spring.datasource.password=security123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jackson.serialization.write-dates-as-timestamps=false

server.port=8082

# Permitir que spring reconozca las cabeceras X-Forwarded-* enviagas por Nginx
server.forward-headers-strategy=framework

# Servicio de correo
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=19030347@itesa.edu.mx
spring.mail.password=uelbtrbrhajtuilg
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

logging.level.org.springframework.web.cors=DEBUG